/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as StudentCreationsRouteImport } from './routes/student-creations'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsWorkshopsRouteImport } from './routes/programs/workshops'
import { Route as ProgramsUpskillingRouteImport } from './routes/programs/upskilling'
import { Route as ProgramsMasterclassesRouteImport } from './routes/programs/masterclasses'
import { Route as ProgramsCustomRouteImport } from './routes/programs/custom'
import { Route as ProgramsAiUpskillingRouteImport } from './routes/programs/ai-upskilling'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCreationsRoute = StudentCreationsRouteImport.update({
  id: '/student-creations',
  path: '/student-creations',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsWorkshopsRoute = ProgramsWorkshopsRouteImport.update({
  id: '/programs/workshops',
  path: '/programs/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsUpskillingRoute = ProgramsUpskillingRouteImport.update({
  id: '/programs/upskilling',
  path: '/programs/upskilling',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsMasterclassesRoute = ProgramsMasterclassesRouteImport.update({
  id: '/programs/masterclasses',
  path: '/programs/masterclasses',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsCustomRoute = ProgramsCustomRouteImport.update({
  id: '/programs/custom',
  path: '/programs/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsAiUpskillingRoute = ProgramsAiUpskillingRouteImport.update({
  id: '/programs/ai-upskilling',
  path: '/programs/ai-upskilling',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/student-creations': typeof StudentCreationsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/programs/ai-upskilling': typeof ProgramsAiUpskillingRoute
  '/programs/custom': typeof ProgramsCustomRoute
  '/programs/masterclasses': typeof ProgramsMasterclassesRoute
  '/programs/upskilling': typeof ProgramsUpskillingRoute
  '/programs/workshops': typeof ProgramsWorkshopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/student-creations': typeof StudentCreationsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/programs/ai-upskilling': typeof ProgramsAiUpskillingRoute
  '/programs/custom': typeof ProgramsCustomRoute
  '/programs/masterclasses': typeof ProgramsMasterclassesRoute
  '/programs/upskilling': typeof ProgramsUpskillingRoute
  '/programs/workshops': typeof ProgramsWorkshopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/student-creations': typeof StudentCreationsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/programs/ai-upskilling': typeof ProgramsAiUpskillingRoute
  '/programs/custom': typeof ProgramsCustomRoute
  '/programs/masterclasses': typeof ProgramsMasterclassesRoute
  '/programs/upskilling': typeof ProgramsUpskillingRoute
  '/programs/workshops': typeof ProgramsWorkshopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy-policy'
    | '/student-creations'
    | '/terms-of-service'
    | '/programs/ai-upskilling'
    | '/programs/custom'
    | '/programs/masterclasses'
    | '/programs/upskilling'
    | '/programs/workshops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy-policy'
    | '/student-creations'
    | '/terms-of-service'
    | '/programs/ai-upskilling'
    | '/programs/custom'
    | '/programs/masterclasses'
    | '/programs/upskilling'
    | '/programs/workshops'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy-policy'
    | '/student-creations'
    | '/terms-of-service'
    | '/programs/ai-upskilling'
    | '/programs/custom'
    | '/programs/masterclasses'
    | '/programs/upskilling'
    | '/programs/workshops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  StudentCreationsRoute: typeof StudentCreationsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ProgramsAiUpskillingRoute: typeof ProgramsAiUpskillingRoute
  ProgramsCustomRoute: typeof ProgramsCustomRoute
  ProgramsMasterclassesRoute: typeof ProgramsMasterclassesRoute
  ProgramsUpskillingRoute: typeof ProgramsUpskillingRoute
  ProgramsWorkshopsRoute: typeof ProgramsWorkshopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-creations': {
      id: '/student-creations'
      path: '/student-creations'
      fullPath: '/student-creations'
      preLoaderRoute: typeof StudentCreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/workshops': {
      id: '/programs/workshops'
      path: '/programs/workshops'
      fullPath: '/programs/workshops'
      preLoaderRoute: typeof ProgramsWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/upskilling': {
      id: '/programs/upskilling'
      path: '/programs/upskilling'
      fullPath: '/programs/upskilling'
      preLoaderRoute: typeof ProgramsUpskillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/masterclasses': {
      id: '/programs/masterclasses'
      path: '/programs/masterclasses'
      fullPath: '/programs/masterclasses'
      preLoaderRoute: typeof ProgramsMasterclassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/custom': {
      id: '/programs/custom'
      path: '/programs/custom'
      fullPath: '/programs/custom'
      preLoaderRoute: typeof ProgramsCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/ai-upskilling': {
      id: '/programs/ai-upskilling'
      path: '/programs/ai-upskilling'
      fullPath: '/programs/ai-upskilling'
      preLoaderRoute: typeof ProgramsAiUpskillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  StudentCreationsRoute: StudentCreationsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ProgramsAiUpskillingRoute: ProgramsAiUpskillingRoute,
  ProgramsCustomRoute: ProgramsCustomRoute,
  ProgramsMasterclassesRoute: ProgramsMasterclassesRoute,
  ProgramsUpskillingRoute: ProgramsUpskillingRoute,
  ProgramsWorkshopsRoute: ProgramsWorkshopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
